version: '3'

services:
  hiroshi:
   restart: unless-stopped
   image: pysergio/hiroshi:latest
   environment:
     TELEGRAM_BOT_TOKEN: 6542608958:AAF_pZe9t48p6VQgNsy2PX8mVehmbEFpdSY
     USERS_WHITELIST: "@YouUserName,@YourFriendUserNamedUserName"
     REDIS: "redis://redis"

  redis:
    restart: unless-stopped
    image: redis:6-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
